### PR TITLE
spm support

### PR DESCRIPTION
**Pull request by uziwuzzy**
1. support spm
2. fix sdk version on analytics

### CODE REVIEW

**Review by askur87 — APPROVED** [review]
LGTM

**Comment by momoohidayat** [comment]
@uziwuzzy any timeline for this PR to be released?

**Comment by uziwuzzy** [comment]
@momoohidayat currently still on preparation stage, hopefully we can release next week.

**Comment by momoohidayat** [comment]
@uziwuzzy any update on the ETA for this to be released?

**Pull request merged**
